CREATE TABLE TASK (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(25) NOT NULL,
  description VARCHAR(50),
  dueDate DATE,
  status VARCHAR(15)
);

CREATE TABLE USER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(20),
  last_name VARCHAR(20)
);

CREATE TABLE LOCATION (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lat DOUBLE,
  lng DOUBLE,
  place VARCHAR(40)
);